[package]
name = "axon"
version = "0.1.0"
edition = "2021"

[dependencies]
gltf = "1.4.1"
iced = {version = "0.13.1", features = ["advanced"]}
iced_aw = "0.12.2"
plotters = "0.3.7"
plotters-iced = "0.11.0"
rfd = "0.15.3"
thiserror = "2.0.12"

[dev-dependencies]
approx = "0.5.1"